import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/app/_styles/global.css";
import MobileHeader from "@/app/_components/mobile-header";
import DesktopHeader from "@/app/_components/desktop-header";
import ThemeWrapper from "@/app/_components/theme-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeWrapper
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen w-full items-center">
            <div className="flex flex-col h-screen w-full md:w-10/12">
              <MobileHeader />
              <DesktopHeader />
              {children}
            </div>
          </div>
        </ThemeWrapper>
      </body>
    </html>
  );
}
